#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6475134035                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : # https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Master Japanese with Real-World News.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jackson Darrow                                
your_link                                 : # https://emilbaehr.com                     
your_city                                 : New York City
email_address                             : jackson.darrow@gmail.com
facebook_username                         :                                           
instagram_username                        : # ebaehr
twitter_username                          : # ebaehr
github_username                           : juicypasta
youtube_username                          :
mastodon_link                             : # https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Personalized News Articles
    description                           : Stay informed and learn effectively with news adjusted to your current language proficiency. Use the language difficulty selector on the article view page to match your level perfectly.
    fontawesome_icon_name                 : magic
    
  - title                                 : Interactive Quizzes
    description                           : Reinforce your understanding and retention with quizzes designed to challenge and entertain.
    fontawesome_icon_name                 : star

  - title                                 : Text-to-Speech
    description                           : Improve your pronunciation and listening skills with our high-quality text-to-speech feature, turning written words into spoken language.
    fontawesome_icon_name                 : play-circle

  - title                                 : Saved Vocabulary
    description                           : Build your personalized vocabulary list as you learn, and review it anytime to ensure long-term retention.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : adjust

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
